DROP TABLE IF EXISTS tags;

CREATE TABLE tags(
    id SERIAL PRIMARY KEY,
    tags VARCHAR(250) NOT NULL,
    images_id INTEGER NOT NULL REFERENCES images(id) ON DELETE CASCADE,
    added TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
